CREATE TABLE SESSIONS (
  SESSION_ID NUMBER(2) PRIMARY KEY

);

CREATE TABLE USAGES (
  USAGE_ID NUMBER(2) PRIMARY KEY,
  SESSION_ID VARCHAR
);

CREATE TABLE SESSION_TYPE (
  SESSION_TYPE_ID NUMBER(2) PRIMARY KEY

);

CREATE TABLE DIAMETER_MESSAGES (
  MESSAGE_ID NUMBER(2) PRIMARY KEY

);

CREATE TABLE CONFIG (
    ID NUMBER(2),
    REMOTE_PEER VARCHAR
);

INSERT INTO CONFIG (ID, REMOTE_PEER) VALUES (1, 'aaa://localhost:3838');

COMMIT;
